from typing import List, Dict

# In-memory destination data
destinations: List[Dict] = [
    {
        "id": "1",
        "name": "Paris",
        "country": "France",
        "rating": 4.8,
        "shortDescription": "The city of lights and love.",
        "images": ["/static/images/paris.svg"],
    },
    {
        "id": "2",
        "name": "Tokyo",
        "country": "Japan",
        "rating": 4.7,
        "shortDescription": "Tradition meets the future.",
        "images": ["/static/images/tokyo.svg"],
    },
    {
        "id": "3",
        "name": "New York",
        "country": "USA",
        "rating": 4.6,
        "shortDescription": "The city that never sleeps.",
        "images": ["/static/images/nyc.svg"],
    },
    {
        "id": "4",
        "name": "Barcelona",
        "country": "Spain",
        "rating": 4.5,
        "shortDescription": "Gaudi architecture and Mediterranean vibe.",
        "images": ["/static/images/paris.svg"],
    },
    {
        "id": "5",
        "name": "Sydney",
        "country": "Australia",
        "rating": 4.4,
        "shortDescription": "Harbour city down under.",
        "images": ["/static/images/tokyo.svg"],
    },
    {
        "id": "6",
        "name": "Cape Town",
        "country": "South Africa",
        "rating": 4.3,
        "shortDescription": "Table Mountain views and rich history.",
        "images": ["/static/images/nyc.svg"],
    },
    {
        "id": "7",
        "name": "Reykjavik",
        "country": "Iceland",
        "rating": 4.9,
        "shortDescription": "Gateway to the northern lights.",
        "images": ["/static/images/paris.svg"],
    },
    {
        "id": "8",
        "name": "Rio de Janeiro",
        "country": "Brazil",
        "rating": 4.2,
        "shortDescription": "Beaches, samba and carnival.",
        "images": ["/static/images/tokyo.svg"],
    },
    {
        "id": "9",
        "name": "Cusco",
        "country": "Peru",
        "rating": 4.1,
        "shortDescription": "Historic capital of the Inca Empire.",
        "images": ["/static/images/nyc.svg"],
    },
    {
        "id": "10",
        "name": "Vancouver",
        "country": "Canada",
        "rating": 4.0,
        "shortDescription": "Coastal city surrounded by mountains.",
        "images": ["/static/images/paris.svg"],
    },
    {
        "id": "11",
        "name": "Cairo",
        "country": "Egypt",
        "rating": 3.9,
        "shortDescription": "Home to ancient pyramids and bustling bazaars.",
        "images": ["/static/images/tokyo.svg"],
    },
    {
        "id": "12",
        "name": "Athens",
        "country": "Greece",
        "rating": 4.0,
        "shortDescription": "Cradle of western civilization.",
        "images": ["/static/images/nyc.svg"],
    },
]
